apiVersion: v1
kind: ConfigMap
metadata:
  name: vts-backend-config
  namespace: vts-dev
  labels:
    project: vts-app
data:                       
  NODE_ENV: "development"
  DEBUG_LEVEL: "debug"
  CONNECTION_STRING: "Host=172.18.0.4;Database=tasks;Username=postgres;Password=postgres"