apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vts-backend-secret-ref
  namespace: vts-dev
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: vts-backend-secret
    creationPolicy: Owner
  data:
    - secretKey: GIGACHAT_AUTH_TOKEN
      remoteRef:
        key: vts/dev 
        property: GIGACHAT_AUTH_TOKEN 

    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: vts/dev
        property: TELEGRAM_BOT_TOKEN

    - secretKey: JWT_SECRET
      remoteRef:
        key: vts/dev
        property: JWT_SECRET

    - secretKey: YANDEX_CLIENT_ID
      remoteRef:
        key: vts/dev
        property: YANDEX_CLIENT_ID

    - secretKey: YANDEX_CLIENT_SECRET
      remoteRef:
        key: vts/dev
        property: YANDEX_CLIENT_SECRET

    - secretKey: SMTP_USERNAME
      remoteRef:
        key: vts/dev
        property: SMTP_USERNAME

    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: vts/dev
        property: SMTP_PASSWORD

    - secretKey: SMTP_FROM
      remoteRef:
        key: vts/dev
        property: SMTP_FROM

    - secretKey: FRONTEND_URL
      remoteRef:
        key: vts/dev
        property: FRONTEND_URL

    - secretKey: ELASTIC_SEARCH_URI
      remoteRef:
        key: vts/dev
        property: ELASTIC_SEARCH_URI