apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: vts-dev
spec:
  provider:
    vault:
      server: "http://172.18.0.1:8200" # Vault запущен в Docker, 172.18.0.1 - kind network gateway (docker network inspect kind | grep Gateway)
      path: "vts"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"